name: 'Zalenium Server'
description: 'Start Zalenium (A flexible and scalable container based Selenium Grid with video recording, live preview, basic auth & dashboard)'
author: Ajinkya Deshmukh <jinkiestheone@gmail.com>
branding:
  icon: 'box'  
  color: 'blue'
runs:
  using: 'node12'
  main: 'index.js'
