name: CI

on: [push]

jobs:
  start-zalenium:
    runs-on: ubuntu-latest
    name: ZALENIUM JOB
    steps:
    - uses: actions/checkout@v2
    - run: npm ci    
    - name: start zalenium
      uses: ./
    - name: is zalenium started?
      run: curl http://localhost:4444/status
